configured_endpoints: 13
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/day-moon-development%2Fpost-for-me-8745dc3422fbd27fbf2588732baea610ae2efc133b5385d8f00fe9da11165c5c.yml
openapi_spec_hash: 472cabf8aef0ed87ee459c8b0321e1c5
config_hash: f9f32855cc8db8aa37a9127eaeeec20f
