configured_endpoints: 13
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/day-moon-development%2Fpost-for-me-b52cc7175167bbf2a8565add1b15ea0776c211e2be5fc663a82e383dad285dac.yml
openapi_spec_hash: 38af6faefdcb6bdd15d2c7ea9e6c896a
config_hash: 55e24fe5898cd04a6f4629a4f77e74fb
